### ISSUE TITLE
Karma grants karma when ++ is seen appended to text anywhere on a line

### ISSUE THREAD

**Issue by els-pnw** [marlboromoo/willie-karma#5]
Karma should not grant karma points when the who is not the first string on the line.

Scenario:

> I do not program in C++ ever

Result:
C 1, reason: ever

Expected Result:
willie-karma should not trigger on this and should not grant C karma here.

**Comment by els-pnw** [comment]
negating works the same.  The issue appears to be worst also in that the increase or decrease in karma can actually occur with a space between.

Example:

I see stars -- they are awesome

Results:
stars -1 reason: they are awesome.

**Comment by 0xd3adcafe** [comment]
Fixed in #6.
